x-frank-postgres-env:
  environment: &frank-postgres-env
    POSTGRES_USER: frank
    POSTGRES_PASSWORD: frank
    POSTGRES_DB: frank

services:
  frank-postgres:
    image: postgres:${POSTGRES_VERSION:-14}
    environment: 
      <<: *frank-postgres-env
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5400:5432"
    volumes:
      - frank-postgres-data:/var/lib/postgresql/data
  
  frank-pgadmin:
    profiles:
      - pgadmin
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    user: root
    command: ["/venv/bin/python3", "/pgadmin4/setup.py", "--load-servers", "frank-pgadmin-conf.json", "--user", "admin@wearefrank.nl"]
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wearefrank.nl
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker/frank-postgres-pgadmin/frank-pgadmin-conf.json:/frank-pgadmin-conf.json
      - ./servers.json:/pgadmin4/servers.json
    depends_on:
      - frank-postgres

  frank:
    environment: 
      <<: *frank-postgres-env
      jdbc.datasource.default: jdbc/haalcentraal-connector-postgresql
      jdbc.hostname: frank-postgres
      jdbc.port: 5432
      jdbc.tcpKeepAlive: true
      jdbc.database: frank
    depends_on:
      - frank-postgres

volumes:
  frank-postgres-data: