instance.name=HaalCentraal-Connector
configurations.directory.autoLoad=true
classloader.type=ScanningDirectoryClassLoader
configurations.brp-personen-bevragen-rest.classLoaderType=DirectoryClassLoader
configurations.brp-personen-bevragen-soap.classLoaderType=DirectoryClassLoader
configurations.brp-personen-bevragen-outway.classLoaderType=DirectoryClassLoader
configurations.subscription-management-and-processing.classLoaderType=DirectoryClassLoader
configurations.oauth.classLoaderType=DirectoryClassLoader
configurations.shadow.classLoaderType=DirectoryClassLoader

# environment options: production, staging, test
environment=test

# Diginet endpoints, based on environment
endpoint.brp.diginet=${endpoint.brp.diginet.${environment}}
oauth.token.url=${oauth.token.url.${environment}}
oauth.token.url.production=https://auth.idm.diginetwerk.net/nidp/oauth/nam/token
oauth.token.url.staging=https://auth.npr.idm.diginetwerk.net/nidp/oauth/nam/token
endpoint.brp.diginet.staging=https://apigw.npr.idm.diginetwerk.net/lap/api/brp/personen
endpoint.brp.diginet.production=https://apigw.idm.diginetwerk.net/api/brp/personen

# (automatic) oauth configuration, based on environment
brp.oauth.enabled=${brp.${environment}.oauth.enabled}
brp.staging.oauth.enabled=true
brp.production.oauth.enabled=true
brp.test.oauth.enabled=false

# Disable output streaming (seems not to be disabled by default in 7.9-SNAPSHOT (in 7.8 it is))
streaming.auto=false
manageDatabase.webServiceListener.active=true
wsdl.caching=false

warnings.suppress.sqlInjections.ManageDatabase=true
manageDatabase.active = false
jdbc.migrator.active=true

NotificationProcessorApi.active=false

ibistesttool.custom=Custom
# Useful to prevent large messages from being truncated in Ladybug but can give Java heap space errors
# ibistesttool.maxMemoryUsage=1000000000
# ibistesttool.maxFileSize=10MB
# ibistesttool.maxMessageLength=10000000

# defaultValue for gemeenteVanInschrijving
gemeenteVanInschrijving=0518

applicationConfigPath=${configurations.directory}/subscription-management-and-processing/json/ApplicationConfig.json
haalcentraal.BRP.personen.bevragen.endpoint.proefomgeving=https://proefomgeving.haalcentraal.nl/haalcentraal/api/brp
lokaal.haalcentraal.BRP.personen.bevragen.endpoint=http://localhost:5001/haalcentraal/api/brp
kadaster.BRK.Bevragen.API=https://api.brk.kadaster.nl/esd-eto-apikey/bevragen/v2
#isDiginetwerk=false <-- default is already false. This property is overridden during deployment
MAX_RETRIES=3

haalcentraal_connector.notification.rest.endpoint=webhooks_brp
haalcentraal_connector.soap.endpoint=haalcentraal_soap
haalcentraal_connector.shadow.endpoint=shadow
haalcentraal_connector.shadow.analitics.endpoint=shadow_analitics

haalcentraal_cert_pass=
haalcentraal_cert_pass_authAlias=diginet.clientCert
haalcentraal_cert_alias=haalcentraal

haalcentraal_connector.endpoint.softfail=false

#Sharedresources
# For backwards compatibility
oauth.token.url=
oauth.scope=
haalcentraal_cert_path=
haalcentraal_cert_pass=
haalcentraal_cert_pass_authAlias=diginet.clientCert
haalcentraal_cert_alias=haalcentraal

#authType options: none, mtls, oauth2
hcc.outway.authType=oauth2

hcc.outway-none-connector.active=false
hcc.outway-mtls-connector.active=false
hcc.outway-oauth2-connector.active=true

hcc.outway.authAlias=
hcc.outway.clientAlias=oauth.credentials
hcc.outway.clientId=
hcc.outway.clientSecret=
hcc.outway.tokenEndpoint=${oauth.token.url}
hcc.outway.oauthAuthenticationMethod=CLIENT_CREDENTIALS_BASIC_AUTH
hcc.outway.scope=${oauth.scope}

hcc.outway.proxy.host=
hcc.outway.proxy.port=
hcc.outway.proxy.authAlias=

hcc.outway.keystore.uri=${haalcentraal_cert_path}
hcc.outway.keystore.type=PKCS12
hcc.outway.keystore.authAlias=
hcc.outway.keystore.alias=${haalcentraal_cert_alias}
hcc.outway.keystore.aliasAuthAlias=${haalcentraal_cert_pass_authAlias}
hcc.outway.keystore.password=${haalcentraal_cert_pass}

hcc.outway.resource.server=ResourceServer01