#
# In this file, all information is stored that are specific for this
# instance of the AdapterFramework.
#
# The values in this file override the values in AppConstants.properties

# suppress warning keys
warnings.suppress.defaultvalue=true

# Public brp endpoint
endpoint.brp.public.test=https://proefomgeving.haalcentraal.nl/haalcentraal/api/brp/personen

#authType options: none, mtls, auth2
hcc.outway.authType=auth2

hcc.outway-${hcc.outway.authType}-connector.active=true


hcc.outway.clientAlias=oauth.credentials
hcc.outway.clientId=
hcc.outway.clientSecret=
hcc.outway.tokenEndpoint=https://auth.idm.diginetwerk.net/nidp/oauth/nam/token
hcc.outway.oauthAuthenticationMethod=CLIENT_CREDENTIALS_BASIC_AUTH
hcc.outway.scope=

hcc.outway.proxy.host=
hcc.outway.proxy.port=
hcc.outway.proxy.authAlias=

hcc.outway.keystore.uri=
hcc.outway.keystore.type=PKCS12
hcc.outway.keystore.authAlias=
hcc.outway.keystore.alias=haalcentraal
hcc.outway.keystore.aliasAuthAlias=diginet.clientCert
hcc.outway.keystore.password=

hcc.outway.resource.server=ResourceServer01