name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  version-next:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version-next: ${{ steps.reference.outputs.next-reference }}
      version-next-strict: ${{ steps.reference.outputs.next-reference }}
    steps:
      - uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2

      - name: Next Reference
        id: reference
        uses: wearefrank/ci-cd-templates/next-reference@00b8c33dd29ef328ad7aa1a2732dc6f41f2e03f3 #2.4.10

  ci:
    uses: wearefrank/ci-cd-templates/.github/workflows/ci-generic.yml@00b8c33dd29ef328ad7aa1a2732dc6f41f2e03f3 #2.4.10
    needs:
      - version-next
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      version: ${{ needs.version-next.outputs.version-next }}
      run-frank-till-healthy-enabled: false

  larva:
    uses: wearefrank/ci-cd-templates/.github/workflows/larva-testrunner.yml@00b8c33dd29ef328ad7aa1a2732dc6f41f2e03f3 #2.4.10
    needs:
      - version-next
      - ci
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    with:
      image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-staging@${{ needs.ci.outputs.image-digest }}
      setup-script: |
        docker run -d --name haalcentraal-connector -p 8080:8080 -e dtap.stage=LOC -e stub4testtool.configuration=true -e stub4testtool.xsl=custom4testtool.xsl -e isDiginetwerk=false -e enableCallback=false -e application.security.console.authentication.type=NONE -e application.security.testtool.authentication.type=NONE "${IMAGE_ID:-${IMAGE_REF}}"
        timeout 300s bash -c 'until [ "$(docker inspect -f "{{.State.Health.Status}}" haalcentraal-connector 2>/dev/null)" == "healthy" ]; do sleep 5; done'
        sleep 10
      teardown-script: |
        docker stop "${CONTAINER_ID}"
        docker rm --volumes "${CONTAINER_ID}"