name: Run Larva Scenarios

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      APP_VERSION:
        type: string
        required: true

jobs:
  run-larva-scenarios:
    runs-on: ubuntu-latest
    steps:
      - name: Run Larva Testrunner action (from repo)
        uses: wearefrank/ci-cd-templates/larva-testrunner@main
        with:
          container-id: haalcentraal-connector